### ISSUE TITLE
Encripción de Base de Datos

### ISSUE THREAD

**Issue by jdiax3004** [jdiax3004/e-Descargas#7]
Investagión de la mejor manera para encriptar

**Comment by jdiax3004** [comment]
Ver laboratorio del profesor

**Comment by Pieza** [comment]
Posible opción: https://www.npmjs.com/package/sequelize-encrypted

**Comment by pieza** [comment]
Se encripta desde el server con cryptojs, requiere confirmacion del profe.

**Comment by pieza** [comment]
Aprobado por el profe
